### ISSUE TITLE
Character Creation Roll tables, some items missing

### ISSUE THREAD

**Issue by Carpenter4269** [Limithron-Foundry-VTT/pirate-borg-system#30]
Foundry Virtual Tabletop: Version 12 Stable, 12.331
Game System: pirateborg, v1.0.1
Active Modules: 4
Performance Mode: 2

OS: Windows 15.0.0 x86 (64-bit)

Character creation compendium menu: 
Only three Containers show in the container compendium , but the Roll table seems to function fine. 
![Containers1](https://github.com/user-attachments/assets/8ee95da4-d6eb-42df-8d1a-7e63a7ef8745)
![Containers2](https://github.com/user-attachments/assets/5c9c1b89-006d-4308-9a07-7aaf29ed9f1b)
![Containers3_RollTable](https://github.com/user-attachments/assets/b6aa1af7-5f75-427f-b98f-97aaeaa683da)

Starting hats roll table, : entry 1-4 are unpopulated, no hat to speak of:
I've included pics of 1-4 results, and a 5th result that represents the rest all working fine. 
Also included the roll table for reference. UUID: Compendium.pirateborg.rolls-character-creation.RollTable.sjglJ6EDdyqC1qh9 

![hats1-3](https://github.com/user-attachments/assets/40d5b299-53c4-4d63-bafc-c73b8b795a94)
![hats2](https://github.com/user-attachments/assets/e36bf374-55d4-489d-9c6e-75a7cb449977)
![hats4](https://github.com/user-attachments/assets/ca590410-65b7-4892-8f55-f0f5cbab652e)
![hats5](https://github.com/user-attachments/assets/030f9473-9e5e-4a2f-b842-496bdf1d259e)
![hatstable](https://github.com/user-attachments/assets/d59d37be-f92f-4090-9dc0-b2c148a41f20)

**Comment by Carpenter4269** [comment]
Found another little character creation bug, D100 roll table for Thing of importance: two items with range of 5
![ThingOfImportance](https://github.com/user-attachments/assets/552b9be1-1e82-4420-83ba-d0efdcdbafd2)

**Comment by sneat** [comment]
Containers:
The other ones are in the `Equipment - Gear` compendium. We didn't want to duplicate them across compendiums (and have two things with different IDs but otherwise the same).

Hats:
Result 1-4 is "no hat". But I can see that's confusing, so we will add a description that you don't get a hat on that roll.

Thing of Importance:
The "animal skull" shouldn't be there. We will remove it in the next release.

Thank you for the reports.

**Comment by Carpenter4269** [comment]
Blair,
Thanks for your quick response!
Glad to help! Everything is wonderful so far. I'm learning Foundry as I go,
so I'm trying to be aware of what could be a real issue and what might
simply be a misunderstanding my attributed to my own learning curve.
Thanks for your explanation of the things I've submitted. That helps me
learn!
- Ben
