### ISSUE TITLE
Sails! Ships at sea macro not populating cargo

### ISSUE THREAD

**Issue by tak5haka** [Limithron-Foundry-VTT/pirate-borg-system#31]
Foundry v12.331
Pirate Borg v1.0.1
Pirate Borg Premium v12.0.1

When executing the "Sails! Ships at sea..." macro, the cargo entry always results in "(0): None". No errors showing in console sadly.

**Comment by sneat** [comment]
Fixed in v12.0.2 of the Pirate Borg Premium module.
