### ISSUE TITLE
Update system to V12

### ISSUE THREAD

**Issue by r-valyar** [Limithron-Foundry-VTT/pirate-borg-system#38]
Are there plans to upgrade the system to support Foundry VTT V12?

**Comment by sneat** [comment]
Hi @r-valyar - the system has supported v12 since release 1.0.0. It just also still supports v11.

Are you seeing any issues?

**Comment by r-valyar** [comment]
The issue was raised some time ago, I think the system was not marked compatible in the system list in Foundry. I see now it is green and since I don't recall any other issue experienced, we can close this :)
